### PR TITLE
Fixes to Spanish language reports page

### LINKED ISSUE #266: Translate each member's rank for Spanish
This is great! We also need a translation for each member's rank (Chair vs Member)

Screenshot 2021-02-02 105117

Edit to https://github.com/edgi-govdata-archiving/EEW-Website/blob/main/src/components/congress/congress.js#L126

_Originally posted by @Frijol in https://github.com/edgi-govdata-archiving/EEW-Website/pull/265#issuecomment-771118730_

### LINKED ISSUE #269: Clarify democratizing data link language
Might want to have more clarity around which reports have been translated, it's non-obvious that the summary report is not translated but the individual reports are. Consider adding "ver el resumen del informe (en ingles)" to the summary report line & "haga clic... en espanol" in the directions for the data visualization

* [x] Translate
* [ ] Implement on site

### LINKED ISSUE #270: Prettier button
image
 spacing is a bit funny, play with this more? @shansen5 is this something you're already doing? If not I'm happy to

### PR DESCRIPTION
**Pull request by Frijol**
Resolving small issues

### CODE REVIEW

**Comment by Frijol** [comment]
Screen Shot 2021-03-18 at 1 50 02 PM
Language edits per #269

**Comment by Frijol** [comment]
Screen Shot 2021-03-18 at 1 57 47 PM

translates ranks

**Comment by Frijol** [comment]
Button:

Screen Shot 2021-03-18 at 2 49 41 PM
with hover effect

Screen Shot 2021-03-18 at 2 50 00 PM

**Comment by shansen5** [comment]
These changes look great to me.

**Review by lesliealanis — APPROVED** [review]

**Comment by lesliealanis** [comment]
I love the button!

**Pull request merged**
