### PR TITLE
New homepage map

### PR DESCRIPTION
**Pull request by CaptainStack**
* Upload new map to assets
* Update homepage to use new image
* Update homepage links to go to all reports page

image

### CODE REVIEW

**Comment by Frijol** [comment]
Updated text on homepage to be relevant/correct for the map shown:
image

Moved the original map to the committee page:
image
image

**Comment by Frijol** [comment]
@ericnost to get you up to speed here: we don't have the carousel working for the homepage yet (and might not for a bit, it's not the next highest priority), but if we push the all-reports changes live, the homepage becomes pretty misleading re what reports are available on the site. So— by using one of your maps on the homepage, we are able to make the still-incomplete homepage at least not misleading. (And we get to show off this gorgeous map.)

We are still planning on getting all the maps live (I'm imagining a carousel on the all-reports page of just your maps), and a carousel on the homepage where we can feature different things. But I think this makes the currently-staged site a lot better.

**Comment by Frijol** [comment]
Pushing to staging so that people can evaluate all the proposed changes together.

**Comment by ericnost** [comment]
Makes sense to me, nice work!

**Pull request merged**
