### PR TITLE
Adds report card map

### LINKED ISSUE #148: Add map image to homepage
* Pull request image into https://github.com/edgi-govdata-archiving/EEW-Website/tree/main/content/home
* Add map to content via markdown where noted in https://github.com/edgi-govdata-archiving/EEW-Website/blob/main/content/home/home-content.md

### PR DESCRIPTION
**Pull request by ericnost**
I fiddled with the design and am most happy with this. But happy for any final feedback.

### CODE REVIEW

**Comment by Frijol** [comment]
might want a more descriptive image name, maybe "eew-map"?

**Comment by Frijol** [comment]
Here it is in setting:

Screen Shot 2020-10-04 at 12 54 31 PM

Aesthetically it feels a bit dark, wondering if we might pick a lighter gray, e.g. #aaa is used somewhere else on the site – or even lighter.

The orange feels pretty intense to me as well. I've been trying to reserve it for calls to action, and I think in this case it makes it seem like we're trying to convey a message about the senators in particular. I wonder if it would work to make the image background white and the senators' states that light green? (..I think that might be what you did originally, which I really liked but I know others had feedback on it too)

Ultimately, I know you've had a lot of feedback on this image! So your call to merge when you're done changing it.

Btw I think I promised you a set of theme colors, here they are: https://github.com/edgi-govdata-archiving/EEW-Website/blob/main/src/constants/theme.js

**Review by Frijol — COMMENTED** [review]
Comments in main thread, essentially:

* More descriptive filename? (If so will also need to update in the .md)
* Thoughts on colors/design

**Comment by ericnost** [comment]
Got it! Thanks for the theme colors. I'll play around a bit. Definitely going to change the background since it was not white on environmentalenforcementwatch.org, but the new site's background is white.

**Comment by ericnost** [comment]
> Aesthetically it feels a bit dark, wondering if we might pick a lighter gray, e.g. #aaa is used somewhere else on the site – or even lighter.

Done! This uses #aaaaaa

> The orange feels pretty intense to me as well. I've been trying to reserve it for calls to action, and I think in this case it makes it seem like we're trying to convey a message about the senators in particular. I wonder if it would work to make the image background white....

Agreed! I've moved away from red, orange, and blue.

> ....and the senators' states that light green? (..I think that might be what you did originally, which I really liked but I know others had feedback on it too)

I have big reservations about shading states for the Senators. To me it results in confusion in states like OR, IL, IN, etc. where we are looking at both Senators and Reps. I want to stick with outlines, but won't use orange red or blue.

I'll await any final feedback then update and merge.

eew

**Comment by ericnost** [comment]
Oh and I think NY needs an outline here as we're looking at Sen. Gillibrand...Not sure why I missed that before.

**Comment by ericnost** [comment]
> More descriptive filename? (If so will also need to update in the .md)

I will make it eew-map.png, so please be sure to update the Markdown. Thanks for catching this!

**Comment by Frijol** [comment]
this looks great!

**Pull request merged**
