### PR TITLE
adding alt text

### PR DESCRIPTION
**Pull request by lesliealanis**
Adding alt text to Congressional District Diagram

### CODE REVIEW

**Comment by lesliealanis** [comment]
https://github.com/edgi-govdata-archiving/EEW-Website/issues/24

**Comment by Frijol** [comment]
Looks good so far! For bonus points, when you add alt text for other images, add them to the same branch you used here. Then they will automatically be added to this pull request.

**Comment by lesliealanis** [comment]
#24

**Comment by Frijol** [comment]
Did you end up resolving in a different branch?

**Pull request closed without merging**
