### PR TITLE
npm audit fix

### PR DESCRIPTION
**Pull request by Frijol**

### CODE REVIEW

**Comment by Frijol** [comment]
this PR fixes a number of npm audit-flagged package dependencies (40-60 of them), but it uses npm's builtin tool, so I don't really know what's happening. I ran the website locally and everything seems fine & works, anybody worried about merging this?

**Comment by Mr0grog** [comment]
Well, the two top-level updates are both testing tools (ava, is the test framework itself, and lighthouse is a general website performance/accessibility testing suite that it looks like ava is being used to run — and that’s the only test it’s running), so the first place to check is probably the tests.

Several of the tests are failing on the `main` branch, but they aren’t even able to run on this branch (likely because the ava v0 → v3 jump introduces some breaking changes we’re running afoul of). I get this output:

```
$ npm test

> gatsby-universal@ test /Users/rbrackett/Dev/datarescue/EEW-Website
> ava **/*.test.js --verbose


  Uncaught exception in scripts/lighthouse.test.js

  scripts/lighthouse.test.js:19

   18: let scores;
   19: test.before(async t => {
   20:   console.log(`Auditing ${siteUrl}.\n`);

  TypeError: Cannot read property 'before' of undefined

  › Object.<anonymous> (scripts/lighthouse.test.js:19:6)

  ✖ scripts/lighthouse.test.js exited with a non-zero exit code: 1
  ─

  1 uncaught exception
```


So I think this probably at least needs some changes to `scripts/lighthouse.test.js` (that’s also the only test file I can find).

**Comment by Mr0grog** [comment]
Ava’s release notes may be helpful: https://github.com/avajs/ava/releases

**Review by Mr0grog — COMMENTED** [review]
Looks like two main things need fixing:

The way `ava` is required in tests: https://github.com/edgi-govdata-archiving/EEW-Website/blob/9c910b906646dba1d9151b4b2b1ca0dba3ff4c7b/scripts/lighthouse.test.js#L2

Should now be:

```js
const test = require('ava');
```

And the tests need a long timeout for lighthouse to do its work. I tried using `t.timeout(60 * 1000)` in the `before` function, but it didn’t seem to be honored. Adding the `--timeout 60s` option on the command-line seemed to work, though.

As far as impacts beyond testing:
- I don’t feel like I know this repo well enough to give a *good* evaluation.
- Since no non-test related top-level dependencies changed, impacts to the site itself seem *unlikely* (there could be some shared dependency that changed in a catastrophic way, but in theory if everything is using semver well, then NPM won’t have thrown things into an incompatible state).

So maybe this repo could use some more tests, but also I think clicking around like you did is probably the best approach to testing this PR for now (outside of the broken tests).

**Comment by Frijol** [comment]
Thanks. To be honest I wasn't aware we had any tests (...which is its own problem) – might have been part of the template?

I'll leave this alone for now

**Pull request closed without merging**
