### PR TITLE
prototypes calendar-centric homepage and moves map to reports page

### PR DESCRIPTION
**Pull request by Frijol**
Makes reports page look like:

Screen Shot 2021-03-18 at 3 16 33 PM
Screen Shot 2021-03-18 at 3 16 47 PM

And homepage kinda like:

Screen Shot 2021-03-18 at 3 17 24 PM
 except where Google can't deal with my repeated test attempts (I can't get the robot thing to go away) we'd have our public calendar

Homepage could use a more engaging image somewhere above the fold to make it look enjoyable (ideas?)

If we like this, we also will need to modify the Spanish version of the reports page to reflect this

### CODE REVIEW

**Comment by Frijol** [comment]
To do:
* [x] Move map back to homepage
* [x] Make the calendar a bit smaller
* [x] Request translation of reports top language

Then push to staging -> production if it looks good

**Comment by Frijol** [comment]
ugh, broken state due to merge conflict confusion. I'll dip back in to fix the English language reports page later. Homepage looks good.

**Comment by Frijol** [comment]
Ok, in order to push this live, we need:

* [x] Team review–this design looks good?
* [x] Translate two paragraphs (below*) to Spanish
* [ ] Make sure the calendar is up to date

*
> Two key congressional committees oversee the EPA to ensure it meets its mandate: the House Energy and Commerce Committee and the Senate Environment and Public Works Committee.

> EEW Congressional Report Cards analyze and present data on violations of environmental laws, inspections of polluting facilities, and enforcement actions by the EPA, to give the members of these Congressional committees–and their constituents–the chance to evaluate whether the EPA is fulfilling its mandate in their state/district.

**Comment by Frijol** [comment]
* [x] Move up calendar
* [x] Add poster for open hour above

**Comment by Frijol** [comment]
merging to staging, @lesliealanis working on the translation and @lourdesvera working on the calendar (I think?)

**Comment by lesliealanis** [comment]
Here are the translated paragraphs:

Hay dos comités del Congreso que supervisan la EPA para garantizar que cumpla con su mandato: el Comité de Energía y Comercio de la Cámara de Representantes y el Comité de Obras Públicas y Medio Ambiente del Senado.

Las boletas de calificaciones del Congreso de EEW analizan y presentan datos sobre las violaciones de las leyes ambientales, las inspecciones de instalaciones contaminantes y las acciones de cumplimiento por parte de la EPA, para darles a los miembros de estos comités del Congreso, y a sus constituyentes, la oportunidad de evaluar si la EPA está cumpliendo con su mandato en su estado / distrito.

**Pull request merged**
