### PR TITLE
working on header changes

### LINKED ISSUE #70: Add EDGI logo to the header? (“an EDGI project”)
from @saraannwylie

### PR DESCRIPTION
**Pull request by Frijol**
Screen Shot 2020-09-16 at 2 00 06 PM

Still needs:
* [x] Vertical alignment of logo with other nav items
* [x] Host the image properly
* [x] In CSS, minimum page width should switch back to text rather than image

resolves https://github.com/edgi-govdata-archiving/EEW-Website/issues/70 when complete

### CODE REVIEW

**Comment by Frijol** [comment]
@ozzmotic or @lightandluck I got the image hosted right but CSS is kind of magic to me, if one of you wants to poke at this branch please go ahead

**Comment by Frijol** [comment]
all my checkboxes are checked but the menu items are weirdly positioned when it's small now

Screen Shot 2020-09-16 at 8 18 36 PM
Screen Shot 2020-09-16 at 8 17 14 PM

**Comment by lightandluck** [comment]
@Frijol 
Just needed to reset alignment on mobile. I also added space around and between the nav items on mobile so folks with big fingers have separate targets, and it lines up better with the logo.
Screen Shot 2020-09-17 at 2 29 10 PM

**Comment by Frijol** [comment]
oh yay, thanks! But I think they should right-align 😬

**Comment by lightandluck** [comment]
Oh, they weren't like that on the staging site. Right-aligned them as asked. I think it looks nicer this way, too.

Screen Shot 2020-09-18 at 3 48 03 PM

**Comment by Frijol** [comment]
yay, thank you!

**Pull request merged**
