### PR TITLE
removed-text-edited-headings

### PR DESCRIPTION
**Pull request by calderEDJ**
I removed the copy: "EEW Report Cards analyze and present data on violations of environmental laws, inspections of polluting facilities, and enforcement actions by the EPA. So far, we’ve generated reports for the congressional districts of each Representative on the House Energy and Commerce Committee (E&C), and for the state of each Senator on the Environment and Public Works Committee (EPW). These two committees are responsible for oversight of the EPA, an agency with a congressional mandate to enforce environmental laws. Our goal is to shed light on the chronic and routine violations of environmental laws and the failure of EPA to enforce them. "
...and will move it to below the interactive graphic.

I also played with the hyperlinked report heading (and added the hyperlink); I tried to make it a heading and center it rather then just have it bolded. I also centered the "select and view completed report cards by representative below:" and made it bolded instead of a header. @Frijol I can't tell exactly how it will look on the finished site so let me know if it looks weird

### CODE REVIEW

**Comment by calderEDJ** [comment]
#232

**Comment by calderEDJ** [comment]
@Frijol now realizing that this will probably mess with the link button you made for "Select and view completed report cards by representative below:" because I got rid of it's status as a heading :/

**Comment by Frijol** [comment]
Oh hm it does look a bit weird 
Screen Shot 2020-10-19 at 3 50 04 PM

**Comment by Frijol** [comment]
We have some options here:

1. I'll reduce some of the vertical spacing around the data visualization, it's too much
2. We have space for some paragraph text above the visualization, I think it would be a good idea to give some context. Specifically Leif suggested (and I agree) that some caveats about the data should come before the reports
3. Another thought for data contextualization: some folks may arrive at this page as their entry point to the EEW project (e.g. someone tweets it). It would be a good idea to have some info for them re what this project is
4. Could remove the page title "EEW Congressional Reports" and just have the report line as the page header (un-center in that case)
5. (Maybe un-center anyway?)

The linking of the header doesn't really matter to me, more important that things look good

**Pull request merged**
